PEWPEW		=	pewpew

CPP			=	c++

CPPFLAGS	=	-Wall -Wextra -Werror -std=c++98

SRC			=	main.cpp

all: $(PEWPEW)

$(PEWPEW)	:
	$(CPP) $(CPPFLAGS) $(SRC) -o $(PEWPEW)

clean		:
	rm -fr $(PEWPEW)

re			: clean all